#!/bin/sh -e

PATH=/bin:/usr/bin:/sbin:/usr/sbin

grep_aptavail_configured () {
	apt-cache $UPDATE_APTCONFIG_ARG dumpavail | grep-dctrl "$@"
}

print_uninstalled_key_packages () {
	grep_aptavail_configured \
		--field=Pragmatux-Key-Package \
		--pattern=1 \
		--exact-match \
		--show-field=Package \
		--no-field-names \
	| while read package
	do
		v_installed=$(grep-status -PX $package \
			--show-field=Version \
			--no-field-names || true)

		if [ -z "$v_installed" ]
		then
			echo -n "$package "
		fi
	done
}

unset config
to_install="$(print_uninstalled_key_packages)"
test -n "$to_install" || exit 0
apt-get -q $UPDATE_APTCONFIG_ARG -y --allow-unauthenticated install $to_install
apt-get -q $UPDATE_APTCONFIG_ARG clean
