#!/bin/sh

PATH=/bin:/usr/bin:/sbin:/usr/sbin:$PATH

apt-get -q $UPDATE_APTCONFIG_ARG -y --allow-unauthenticated dist-upgrade
apt-get -q $UPDATE_APTCONFIG_ARG clean
apt-get -q $UPDATE_APTCONFIG_ARG autoremove
