#!/bin/sh -e

PATH=/bin:/usr/bin:/sbin:/usr/sbin

RETURN_UNREACHABLE=64
RETURN_INVALID=65

die () {
	echo Error: "$@" >&2
	exit 1
}

get_first_archive () {
	cat /etc/apt/sources.list /etc/apt/sources.list.d/* 2>/dev/null \
	| grep '^deb\W\+http' \
	| head -n 1 \
	| { read TAG ARCHIVE DIST REST; echo $ARCHIVE $DIST; }
}

test_archive () {
	ARCHIVE=$1
	DIST=$2
	release_file=$ARCHIVE/dists/$DIST/Release
	http_status=$(curl \
		--url $release_file \
		--write-out '%{response_code}\n' \
		--max-time 15 \
		--silent \
		--output /dev/null) || return $RETURN_UNREACHABLE

	test "$http_status" = "200" || return $RETURN_INVALID
}

update_apt () {
	apt-get update -qq
}

print_outofdate_key_packages () {
	grep-aptavail \
		--field=Pragmatux-Key-Package \
		--pattern=1 \
		--exact-match \
		--show-field=Package \
		--no-field-names \
	| while read package
	do
		v_available=$(grep-aptavail -PX $package \
			--show-field=Version \
			--no-field-names)
		v_installed=$(grep-status -PX $package \
			--show-field=Version \
			--no-field-names || true)

		if [ -n "$v_installed" ] && \
		   dpkg --compare-versions $v_available gt $v_installed
		then
			echo "Package: $package"
			echo "Installed-Version: $v_installed"
			echo "Available-Version: $v_available"
			echo
		fi
	done
}

do_check () {
	test_archive $(get_first_archive)
	update_apt
	print_outofdate_key_packages
}

do_update () {
	apt-get dist-upgrade --allow-unauthenticated -qq
	apt-get clean -qq
	apt-get autoremove -qq
}

case "$1" in
	check)
		do_check
		;;

	update-all)
		do_update
		;;

	*)
		die "Unknown command"
		;;
esac
